name: Upload Changes

on:
    push:
        branches:
            - developement_base

jobs:
    Server_Upload:
        runs-on: ubuntu-latest

        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: execute upload script
          run: |
           chmod +x ./script/change.sh
           ./script/change.sh