name: Upload Changes

on:
    push:
        branches:
            - developement_base

jobs:
    Server_Upload:
        runs-on: ubuntu-latest

        steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: execute zip script
          run: |
           chmod +x ./script/change.sh
           ./script/change.sh
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: changes
            path: changed_files.zip