name: Sync Dev PRs

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    PR_maintainence:
        runs-on: ubuntu-latest

        steps:
        - name: checkout source
          uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}
            path: repo

        - name: checkout base
          uses: actions/checkout@v4
          with:
            ref: ${{ github.base_ref }}
            path: repo

        - name: get diff from base
          run: |
           cd repo
           git checkout ${{github.head_ref}}
           git diff --diff-filter=ACMRT ${{github.base_ref}} ../changes.patch
           grep '^diff --git' ../changes.patch | awk '{ sub(/^a\//,"",$3); print $3 }'

        - name: applying patch to base
          run: |
           cd repo
           git checkout ${{github.base_ref}}
           git config user.name "Dipanker18"
           git config user.email "dipanker.das@cognizant.com"
           git apply  ../changes.patch

        - name: commit and push (PR cleanup)
          run: |
           cd repo
           git checkout ${{github.base_ref}}
           git add .
           git commit -m "Apply clean patch" || echo "No Changes"
           git push origin HEAD:${{ github.head_ref }}
          

            